### PR TITLE
fixed installation error when invalid override instructions present

### LINKED ISSUE #19143: error: Cannot read properties of undefined (reading 'toUpperCase')
#### System
| | |
|------------ | -------------|
|Platform | win32 10.0.26200  |
|CPU Architecture | x64 |
|Architecture | x64 |
|Application Version | 1.16.0-beta.3 |
|Process | renderer |
#### Message
Cannot read properties of undefined (reading 'toUpperCase')
#### Title
```
Installation failed
```

#### Context
```
gamemode = Escape from Duckov,extension_version = 0.1.0,Installing = StackableItems-2-1-3-1-1761251274
```
#### Stack
```
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at G:\VORTEX\resources\app.asar\renderer.js:9119:38
    at Array.map (<anonymous>)
    at InstallManager.processInstructions (G:\VORTEX\resources\app.asar\renderer.js:9118:196)
    at G:\VORTEX\resources\app.asar\renderer.js:8917:14
    at tryCatcher (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)

Reported from:
Error
    at showError (G:\VORTEX\resources\app.asar\renderer.js:5547:18)
    at InstallContext.mShowError (G:\VORTEX\resources\app.asar\renderer.js:11627:21)
    at InstallContext.reportError (G:\VORTEX\resources\app.asar\renderer.js:11651:6)
    at G:\VORTEX\resources\app.asar\renderer.js:8937:132
    at tryCatcher (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (G:\VORTEX\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)
```
 

 
 External file: tmp-18028lwXYu4PFHlBI.7z
 
 Reported by: souran0312

### PR DESCRIPTION
**Pull request by IDCs**
fixes nexus-mods/vortex#19143

### CODE REVIEW

File: src/extensions/mod_management/InstallManager.ts [hunk 1]
```diff
@@ -4280,7 +4280,11 @@ class InstallManager {
     }
     const overrideMap = new Map<string, IInstruction>();
     result.overrideInstructions?.forEach((instr) => {
-      const key = (instr.source ?? instr.type).toUpperCase();
+      let key = instr.source ?? instr.type;
+      if (key == null) {
```
Comment (Aragas) [inline src/extensions/mod_management/InstallManager.ts:4284]: We only expect null? undefined isn't possible?

**Review by Aragas — APPROVED** [review]

File: src/extensions/mod_management/InstallManager.ts (hunk 1 above)
Comment (IDCs) [reply src/extensions/mod_management/InstallManager.ts:4284]: `key == null` will handle both undefined and null
