### PR TITLE
V1.16 small fixes

### LINKED ISSUE #19794: Crash: Cannot read properties of undefined (reading 'collectionRule')
#### System
| | |
|------------ | -------------|
|Platform | win32 10.0.26100  |
|CPU Architecture | x64 |
|Architecture | x64 |
|Application Version | 1.16.1 |
|Process | renderer |
#### Message
Cannot read properties of undefined (reading 'collectionRule')
#### Context
```
gamemode = Cyberpunk 2077,extension_version = 0.12.0,Downloading "nxm://cyberpunk2077/mods/8045/files/42330?campaign=collection" = nxm://cyberpunk2077/mods/8045/files/42330?campaign=collection,Downloading "nxm://cyberpunk2077/mods/10331/files/79988?campaign=collection" = nxm://cyberpunk2077/mods/10331/files/79988?campaign=collection,Downloading "nxm://cyberpunk2077/mods/7089/files/37710?campaign=collection" = nxm://cyberpunk2077/mods/7089/files/37710?campaign=collection,Downloading "nxm://cyberpunk2077/mods/6795/files/36364?campaign=collection" = nxm://cyberpunk2077/mods/6795/files/36364?campaign=collection,Downloading "nxm://cyberpunk2077/mods/6036/files/31732?campaign=collection" = nxm://cyberpunk2077/mods/6036/files/31732?campaign=collection
```
#### Stack
```
TypeError: Cannot read properties of undefined (reading 'collectionRule')
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\collections\index.js:2:290929
    at Array.map (<anonymous>)
    at Object.installManually [as action] (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\collections\index.js:2:290917)
    at triggerDefault (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:1669:239)
    at Object.ba (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:14:84)
    at ja (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:14:238)
    at ka (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:14:292)
    at oa (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:15:72)
    at lc (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:52:146)
    at jc (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:51:255)
    at mc (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:52:334)
    at sc (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:56:10)
    at Ia (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:287:189)
    at Ma (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:19:57)
    at Rc (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:70:279)
    at id (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:69:102)
```
 

 
 External file: tmp-1912l0gFYfLzK7uy.7z
 
 Reported by: Hidden344

### LINKED ISSUE #19844: error: Cannot read properties of undefined (reading 'site')
#### System
| | |
|------------ | -------------|
|Platform | win32 10.0.26200  |
|CPU Architecture | x64 |
|Architecture | x64 |
|Application Version | 1.16.2 |
|Process | renderer |
#### Message
Cannot read properties of undefined (reading 'site')
#### Title
```
Download failed
```

#### Stack
```
TypeError: Cannot read properties of undefined (reading 'site')
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:11570:147
    at makeFileUID (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:11571:76)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:10549:83
    at Promise.cancellationExecute [as _execute] (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\debuggability.js:406:9)
    at Promise._resolveFromExecutor (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:103:10)
    at getInfoGraphQL (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:10549:9)
    at startDownloadMod (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:10472:9)
    at startDownload (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:10496:2)
    at downloadFile (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:2020:158)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:1940:185
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:97:12)

Reported from:
Error
    at showError (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:5539:18)
    at mApi.showErrorNotification (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:9605:52)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:10495:80
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)
```
 

 
 Reported by: Terminater743

### LINKED ISSUE #19885: error: Cannot read properties of undefined (reading 'id')
#### System
| | |
|------------ | -------------|
|Platform | win32 10.0.26200  |
|CPU Architecture | x64 |
|Architecture | x64 |
|Application Version | 1.16.2 |
|Process | renderer |
#### Message
Cannot read properties of undefined (reading 'id')
#### Title
```
Failed to install dependencies
```

#### Context
```
gamemode = Fallout 4,extension_version = 1.0.7
```
#### Stack
```
TypeError: Cannot read properties of undefined (reading 'id')
    at InstallManager.installDependencies (D:\Vortex\resources\app.asar\renderer.js:8948:119)
    at D:\Vortex\resources\app.asar\renderer.js:1405:54
    at tryCatcher (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\map.js:68:38)
    at PromiseArray._iterate (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise_array.js:115:31)
    at MappingPromiseArray.init (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\map.js:37:10)
    at _drainQueueStep (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)

Reported from:
Error
    at showError (D:\Vortex\resources\app.asar\renderer.js:5539:18)
    at mApi.showErrorNotification (D:\Vortex\resources\app.asar\renderer.js:9605:52)
    at D:\Vortex\resources\app.asar\renderer.js:1406:5
    at tryCatcher (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (D:\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)
```
 

 
 Reported by: MidgetPat

### LINKED ISSUE #19921: error: Cannot read properties of undefined (reading 'attributes')
#### System
| | |
|------------ | -------------|
|Platform | win32 10.0.26200  |
|CPU Architecture | x64 |
|Architecture | x64 |
|Application Version | 1.16.2 |
|Process | renderer |
#### Message
Cannot read properties of undefined (reading 'attributes')
#### Title
```
Installation failed
```

#### Context
```
gamemode = Stardew Valley,extension_version = 0.3.9
```
#### Stack
```
TypeError: Cannot read properties of undefined (reading 'attributes')
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:9189:222
    at Array.map (<anonymous>)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:9189:177
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)

Reported from:
Error
    at showError (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:5539:18)
    at InstallContext.mShowError (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:11531:21)
    at InstallContext.reportError (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:11555:6)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:8936:132
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)
```
 

 
 External file: tmp-13100ViNybXkC7wna.7z
 
 Reported by: xbriii

### LINKED ISSUE #20082: error: Cannot read properties of undefined (reading 'logicalFileName')
#### System
| | |
|------------ | -------------|
|Platform | win32 10.0.26200  |
|CPU Architecture | x64 |
|Architecture | x64 |
|Application Version | 1.16.2 |
|Process | renderer |
#### Message
Cannot read properties of undefined (reading 'logicalFileName')
#### Title
```
Failed to install dependencies
```

#### Context
```
gamemode = Baldur's Gate 3,extension_version = 1.5.7,Downloading "nxm://baldursgate3/mods/18794/files/103614?campaign=collection" = nxm://baldursgate3/mods/18794/files/103614?campaign=collection,Downloading "nxm://baldursgate3/mods/11456/files/66661?campaign=collection" = nxm://baldursgate3/mods/11456/files/66661?campaign=collection,Downloading "nxm://baldursgate3/mods/14698/files/89250?campaign=collection" = nxm://baldursgate3/mods/14698/files/89250?campaign=collection,Downloading "ATEEZ Comeback - Regular Version-21023-3-0-0-0-1770187087.zip" = nxm://baldursgate3/mods/21023/files/114083?campaign=collection,Downloading "Babymetal - UTAV-18322-1-0-0-0-1756392166.zip" = nxm://baldursgate3/mods/18322/files/101584?campaign=collection,Downloading "Bambi's Rosalie UTAV-15657-3-0-1761337645.zip" = nxm://baldursgate3/mods/15657/files/105928?campaign=collection,Downloading "Bambi's Rosalie VAMP UTAV-15657-3-0-1761337786.zip" = nxm://baldursgate3/mods/15657/files/105933?campaign=collection,Downloading "nxm://baldursgate3/mods/8298/files/51615?campaign=collection" = nxm://baldursgate3/mods/8298/files/51615?campaign=collection,Downloading "nxm://baldursgate3/mods/14873/files/85255?campaign=collection" = nxm://baldursgate3/mods/14873/files/85255?campaign=collection,Downloading "Main File-18990-1-1-1762015775.zip" = nxm://baldursgate3/mods/18990/files/106529?campaign=collection,Downloading "nxm://baldursgate3/mods/12122/files/72665?campaign=collection" = nxm://baldursgate3/mods/12122/files/72665?campaign=collection,Downloading "Ezuneo's Piercings - Eye-coloured Potions-17042-2-0-1756586934.zip" = nxm://baldursgate3/mods/17042/files/101733?campaign=collection,Downloading "nxm://baldursgate3/mods/12122/files/81980?campaign=collection" = nxm://baldursgate3/mods/12122/files/81980?campaign=collection,Downloading "nxm://baldursgate3/mods/12122/files/85816?campaign=collection" = nxm://baldursgate3/mods/12122/files/85816?campaign=collection,Downloading "Faces of Faerun-429-2-2-0-0-1745143905.zip" = nxm://baldursgate3/mods/429/files/89851?campaign=collection,Downloading "nxm://baldursgate3/mods/9987/files/92755?campaign=collection" = nxm://baldursgate3/mods/9987/files/92755?campaign=collection,Downloading "nxm://baldursgate3/mods/6507/files/43321?campaign=collection" = nxm://baldursgate3/mods/6507/files/43321?campaign=collection,Downloading "nxm://baldursgate3/mods/12141/files/70838?campaign=collection" = nxm://baldursgate3/mods/12141/files/70838?campaign=collection,Downloading "Fairy Hairstyle by Lee Yiplee 1.8-12022-1-8-1731554674.zip" = nxm://baldursgate3/mods/12022/files/78855?campaign=collection,Downloading "Fairy Hairstyle No Bangs by Lee Yiplee 1.8-12022-1-8-1731554755.zip" = nxm://baldursgate3/mods/12022/files/78856?campaign=collection,Downloading "fancy noble gear-5397-3-1726752073.zip" = nxm://baldursgate3/mods/5397/files/71792?campaign=collection,Downloading "FANG's Dress-14858-1-0-0-0-1738387411.zip" = nxm://baldursgate3/mods/14858/files/85132?campaign=collection,Downloading "FelineStarterPack-11931-1-0-0-1725223524.zip" = nxm://baldursgate3/mods/11931/files/68540?campaign=collection
```
#### Stack
```
TypeError: Cannot read properties of undefined (reading 'logicalFileName')
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:9247:161
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)

Reported from:
Error
    at showError (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:5539:18)
    at mApi.showErrorNotification (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:9605:52)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:9253:172
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)
```
 

 
 Reported by: TheDoomguy2177

### LINKED ISSUE #20380: Crash: Cannot read properties of undefined (reading 'find')
#### System
| | |
|------------ | -------------|
|Platform | win32 10.0.26200  |
|CPU Architecture | x64 |
|Architecture | x64 |
|Application Version | 1.16.2 |
|Process | renderer |
#### Message
Cannot read properties of undefined (reading 'find')
#### Context
```
gamemode = Fallout 4,extension_version = 1.0.7
```
#### Stack
```
TypeError: Cannot read properties of undefined (reading 'find')
    at D:\New folder\Vortex\resources\app.asar\renderer.js:1515:118
    at Array.reduce (<anonymous>)
    at D:\New folder\Vortex\resources\app.asar\renderer.js:1514:208
    at Object.ba (D:\New folder\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:14:84)
    at ja (D:\New folder\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:14:238)
    at ka (D:\New folder\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:14:292)
    at oa (D:\New folder\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:15:72)
    at lc (D:\New folder\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:52:146)
    at jc (D:\New folder\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:51:255)
    at mc (D:\New folder\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:52:334)
    at sc (D:\New folder\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:56:10)
    at Ia (D:\New folder\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:287:189)
    at Ma (D:\New folder\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:19:57)
    at Rc (D:\New folder\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:70:279)
    at id (D:\New folder\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:69:102)
    at exports.unstable_runWithPriority (D:\New folder\Vortex\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:19:467)
```
 

 
 External file: tmp-8644RKeYhSCPknRK.7z
 
 Reported by: Omaof9

### PR DESCRIPTION
**Pull request by Aragas**
Fixed #19794
Fixed #19844
Fixed #19885
Fixes #19921
Fixes #20380
Fixes #20082

### CODE REVIEW

File: src/extensions/mod_management/InstallManager.ts [hunk 1]
```diff
@@ -4983,13 +4983,13 @@ class InstallManager {
           "Select Variant to Replace",
           {
             text: '"{{modName}}" has several variants installed - please choose which one to replace:',
-            choices: modIds.map((id, idx) => {
```
Comment (IDCs) [inline src/extensions/mod_management/InstallManager.ts:4986]: What happened to the `modIds` array? is it still being used or can it be removed?

Comment (IDCs) [reply src/extensions/mod_management/InstallManager.ts:4986]: Can see that it's still needed - nevermind

**Review by IDCs — APPROVED** [review]

**Comment by IDCs** [comment]
The windows build failure is down to zlib changing release paths (looks like a yearly practice). Going to merge this in as the fix for zlib is on master.

**Comment by IDCs** [comment]
@Aragas can you cherry-pick these into master please?
